name: 'Push protein paint image'

on:
  workflow_dispatch:
env:
  ACR_NAME: sjcmpbdtacr
  ACR_SERVER: sjcmpbdtacr.azurecr.io
  ACR_REPO: sjcmpbdtacr.azurecr.io/pp_clingen
jobs:
  print-values:
    runs-on: ubuntu-latest

    steps:
      - name: Set values for A and b
        run: |
          A="Value for A"
          b="Value for b"
          echo "A: $A"
          echo "b: $b"
